//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.0
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secs4Net.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Secs4Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Unrecognized Device Id 的當地語系化字串。
        /// </summary>
        internal static string S9F1 {
            get {
                return ResourceManager.GetString("S9F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data Too Long 的當地語系化字串。
        /// </summary>
        internal static string S9F11 {
            get {
                return ResourceManager.GetString("S9F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Conversation Timeout 的當地語系化字串。
        /// </summary>
        internal static string S9F13 {
            get {
                return ResourceManager.GetString("S9F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unrecognized Stream Type 的當地語系化字串。
        /// </summary>
        internal static string S9F3 {
            get {
                return ResourceManager.GetString("S9F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unrecognized Function Type 的當地語系化字串。
        /// </summary>
        internal static string S9F5 {
            get {
                return ResourceManager.GetString("S9F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Illegal Data 的當地語系化字串。
        /// </summary>
        internal static string S9F7 {
            get {
                return ResourceManager.GetString("S9F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transaction Timer Timeout 的當地語系化字串。
        /// </summary>
        internal static string S9F9 {
            get {
                return ResourceManager.GetString("S9F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 S9Fy message reply. 的當地語系化字串。
        /// </summary>
        internal static string S9Fy {
            get {
                return ResourceManager.GetString("S9Fy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Equipment is not online mode 的當地語系化字串。
        /// </summary>
        internal static string SxF0 {
            get {
                return ResourceManager.GetString("SxF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 T3 Timeout! 的當地語系化字串。
        /// </summary>
        internal static string T3Timeout {
            get {
                return ResourceManager.GetString("T3Timeout", resourceCulture);
            }
        }
    }
}
